<a href="https://colab.research.google.com/github/maheshkajjari/Comparison_operators_template-1-.ipynb/blob/master/Comparison_operators_template(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Comparison Operators

In [ ]:
import numpy as np
np_length = np.array([2.7, 3.4, 4.7, 6.6, 7.8])
np_breath = np.array([3.7, 1.4, 2.7, 3.6, 1.8])
np_height = np.array([1.7, 2.4, 1.7, 0.6, 1.8])
vol_cuboid = np_length * np_breath * np_height
vol_cuboid

array([16.983, 11.424, 21.573, 14.256, 25.272])

Show the vol_cuboid which are greater than 15

In [ ]:
 print("Input")
a = np.array([16.983, 11.424, 21.573, 14.256, 25.272])
a
print("Solution")
a[(a > 15)]

Input
Solution


array([16.983, 21.573, 25.272])

## Numeric & Variable Comparison

Using comparison operators show:

Q1. If 10.5 is greater thean 10

Q2. If 10.5 is greater than equal to 10.5

Q3. If 20 is equal to 20.1

Q4. If Ansh is greater than Anshu

Q5. If Monkey is greater than 5

In [ ]:
x = np.array([10.5])
print('Original Array = ', 10.5)
print('\nGreater Than  = ', np.greater(x, 10))
 

Original Array =  10.5

Greater Than eual to  =  [ True]


In [ ]:
x = np.array([10.5])
print('Original Array = ', 10.5)
print('\nGreater Than equal to = ', np.greater_equal(x, 10))

Original Array =  10.5

Greater Than equal to =  [ True]


In [ ]:
# 4
## Start code here

## End here

In [ ]:
# 5
## Start code here

## End here

## Boolean Operators

1. and
2. or
3. not

Q1. Use and operator to check if x is greater than 2 and less than 10

Q2. Use or operator to check if x is grater than 3 and less than 10

Q3. Use not operator to check if x is greater than 5 and less than 8

In [ ]:
c = np.array([2, 6, 1, 9, 10, 3, 27])
c

array([ 2,  6,  1,  9, 10,  3, 27])

In [ ]:
 c[(c > 2) & (c < 10)]
 

array([6, 9, 3])

In [ ]:
 c[(c > 3) & (c < 10)]

array([6, 9])

In [ ]:
c[(c > 5) & (c < 8)]

## End here

array([6])

## Numpy

1. logical_and()
2. logical_or()
3. logical_not()

Q1. Use the logical_and operator to check if vol_cuboid is greater than 11 and less than 20

Q2. Use the logical_or operator to check if vol_cuboid is greater than 11 and less than 20

Q3. Use the logical_not operator to check if vol_cuboid is greater than 11 and less than 20

In [ ]:
  x = vol_cuboid
  np.logical_and(x > 11, x < 20)

array([False, False, False, False, False])

In [ ]:
 x = vol_cuboid

np.logical_or(x < 20, x > 11)

array([ True,  True,  True,  True,  True])

In [ ]:
 x = vol_cuboid
 np.logical_not(x < 20, x > 11)

array([False, False, False, False, False])

## if , elif , else

In [ ]:
a = 100
b = 10

Q1. Use if condition statment to check if a is greater than b and print the greatest number.

Q2. Use else condition statment to check if b is greater or less than a and print the greatest number.

Q3. Use elif condition statment to check if b is greater , less than or equal to a and print the greatest number.

In [ ]:

a = float(input(" Please Enter the First Value a: "))
b = float(input(" Please Enter the Second Value b: "))

if(a > b):
    print("{0} is Greater than {1}".format(a, b))
elif(b > a):
    print("{0} is Greater than {1}".format(b, a))
else:
    print("Both a and b are Equal")

 Please Enter the First Value a: 100
 Please Enter the Second Value b: 10
100.0 is Greater than 10.0


## Filtering pandas Dataframes

In [ ]:
df = {
    "Name": ["aparna", "pankaj", "sudhir", "Geeku", "Chiku", "Jeniffer"], 
    "Degree": ["Bsc", "Engineering", "Law", "MBBS", "Phd", "Nursing"],
    "College": ["VIT", "IIT", "KIIT", "AIMS", "IIIT", "APPOLO"],
    "Score": [90, 70, 80, 98, 76, 89]} 

import pandas as pd
dataframe = pd.DataFrame(df)
dataframe

Name       Degree College  Score
0    aparna          Bsc     VIT     90
1    pankaj  Engineering     IIT     70
2    sudhir          Law    KIIT     80
3     Geeku         MBBS    AIMS     98
4     Chiku          Phd    IIIT     76
5  Jeniffer      Nursing  APPOLO     89

Q1. Access the Score column

Q2. Use comparison operator to show which students has score greater than 80

Q3. Use logical_and operator to see scores greater than 75 and less than 90

In [ ]:
df['Score']

[90, 70, 80, 98, 76, 89]

In [ ]:
np.greater(x, 80))

In [ ]:
  np.logical_and(x > 75, x < 90)